### ISSUE TITLE
Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference

### ISSUE THREAD

**Issue by faisalur-rehman** [pushy/pushy-react-native#84] opened 2023-03-27 07:22 UTC
@eggli @pushy Firebase crashlytics has detected this crash on android. Every user is facing this crash. I am using following versions:
`"pushy-react-native": "^1.0.29",`
`"react-native": "0.70.5",`

<img width="1171" alt="Screenshot 2023-03-27 at 11 55 03 AM" src="https://user-images.githubusercontent.com/66237466/227868502-284a729d-c823-4b9c-8f35-50d1bf6f68bb.png">

**Comment by pushy** [comment] 2023-03-31 11:08
Hi @faisalur-rehman,
Thanks for your patience and for your response.

This issue has now been fixed in the latest version of the Pushy React Native Android SDK.

Please import version `1.0.19` of the Pushy React Native Android SDK by updating the following dependency in your `android/app/build.gradle`, within the `dependencies {}` declaration:
```
// Pushy SDK for React Native Android
implementation 'me.pushy:sdk-react-native:1.0.19'
```

Then, re-build and re-run your app, and the issue will be resolved. We apologize for any inconvenience caused by this issue.

**Closed by pushy** 2023-03-31 11:08 UTC
