### ISSUE TITLE
Exception java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference

### ISSUE THREAD

**Issue by wynandjordaan** [pushy/pushy-react-native#85] opened 2023-03-31 09:46 UTC
We are getting multiple crash reports from Android on the following:
```
Exception java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
  at me.pushy.sdk.util.PushyPersistence.getEnvironmentExternalStoragePath (PushyPersistence.java:57)
  at me.pushy.sdk.util.PushyAuthentication.getDeviceCredentials (PushyAuthentication.java:28)
  at me.pushy.sdk.Pushy.register (Pushy.java:210)
  at me.pushy.sdk.react.modules.PushyModule$1.run (PushyModule.java:78)
  at android.os.AsyncTask$SerialExecutor$1.run (AsyncTask.java:289)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
  at java.lang.Thread.run (Thread.java:919)
```

I am not sure why this is failing as I cannot even reproduce this on my phones.

Please help.

**Comment by pushy** [comment] 2023-03-31 11:07
Hi @wynandjordaan,
Thanks for reaching out. We'd be glad to assist in resolving this issue.

This issue has been fixed in the latest version of the Pushy React Native Android SDK.

Please import version `1.0.19` of the Pushy React Native Android SDK by updating the following dependency in your `android/app/build.gradle`, within the `dependencies {}` declaration:
```
// Pushy SDK for React Native Android
implementation 'me.pushy:sdk-react-native:1.0.19'
```

Then, re-build and re-run your app, and the issue will be resolved. We apologize for any inconvenience caused by this issue.

**Closed by pushy** 2023-03-31 11:07 UTC
